# Generated by Django 4.1.1 on 2022-10-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20191207_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalacademicyear',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical academic year', 'verbose_name_plural': 'historical academic years'},
        ),
        migrations.AlterModelOptions(
            name='historicalactivitytype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical activity type', 'verbose_name_plural': 'historical activity types'},
        ),
        migrations.AlterModelOptions(
            name='historicalengagementactivitytype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical engagement activity type', 'verbose_name_plural': 'historical engagement activity types'},
        ),
        migrations.AlterModelOptions(
            name='historicalengagementtype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical engagement type', 'verbose_name_plural': 'historical engagement types'},
        ),
        migrations.AlterModelOptions(
            name='historicalmissionsubcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical mission sub category', 'verbose_name_plural': 'historical mission sub categorys'},
        ),
        migrations.AlterModelOptions(
            name='historicalproject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project', 'verbose_name_plural': 'historical projects'},
        ),
        migrations.AlterModelOptions(
            name='historicalprojectcampuspartner',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project campus partner', 'verbose_name_plural': 'historical project campus partners'},
        ),
        migrations.AlterModelOptions(
            name='historicalprojectcommunitypartner',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project community partner', 'verbose_name_plural': 'historical project community partners'},
        ),
        migrations.AlterModelOptions(
            name='historicalprojectengagementactivity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project engagement activity', 'verbose_name_plural': 'historical project engagement activitys'},
        ),
        migrations.AlterModelOptions(
            name='historicalprojectmission',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project mission', 'verbose_name_plural': 'historical project missions'},
        ),
        migrations.AlterModelOptions(
            name='historicalprojectrelatedlink',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project related link', 'verbose_name_plural': 'historical project related links'},
        ),
        migrations.AlterModelOptions(
            name='historicalprojectsubcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project sub category', 'verbose_name_plural': 'historical project sub categorys'},
        ),
        migrations.AlterModelOptions(
            name='historicalstatus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Status', 'verbose_name_plural': 'historical Statuses'},
        ),
        migrations.AlterModelOptions(
            name='historicalsubcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sub category', 'verbose_name_plural': 'historical sub categorys'},
        ),
        migrations.AlterField(
            model_name='historicalacademicyear',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalactivitytype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalengagementactivitytype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalengagementtype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmissionsubcategory',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectcampuspartner',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectcommunitypartner',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectengagementactivity',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectmission',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectrelatedlink',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectsubcategory',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstatus',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsubcategory',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
