# Generated by Django 4.1.1 on 2022-10-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_historicaluniversity_slug_university_slug'),
        ('projects', '0019_alter_historicalacademicyear_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='university',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='university.university'),
        ),
        migrations.AddField(
            model_name='project',
            name='university',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
    ]
