# Generated by Django 4.1.1 on 2022-10-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_alter_historicalcampuspartner_options_and_more'),
        ('home', '0022_alter_user_university'),
        ('projects', '0020_historicalproject_university_project_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='campus_partner',
            field=models.ManyToManyField(to='partners.campuspartner'),
        ),
        migrations.AddField(
            model_name='project',
            name='community_partner',
            field=models.ManyToManyField(to='partners.communitypartner'),
        ),
        migrations.AddField(
            model_name='project',
            name='mission_area',
            field=models.ManyToManyField(to='home.missionarea'),
        ),
    ]
