# Generated by Django 4.1.1 on 2022-10-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_user_university'),
        ('projects', '0021_project_campus_partner_project_community_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='mission_area',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.missionarea'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='mission_area',
        ),
        migrations.AddField(
            model_name='project',
            name='mission_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.missionarea'),
        ),
    ]
