# Generated by Django 4.1.1 on 2022-10-03 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_historicalcollege_options_and_more'),
        ('home', '0020_auto_20191207_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcontact',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contact', 'verbose_name_plural': 'historical contacts'},
        ),
        migrations.AlterModelOptions(
            name='historicaldatadefinition',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical data definition', 'verbose_name_plural': 'historical data definitions'},
        ),
        migrations.AlterModelOptions(
            name='historicalhouseholdincome',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical household income', 'verbose_name_plural': 'historical household incomes'},
        ),
        migrations.AlterModelOptions(
            name='historicalresource',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resource', 'verbose_name_plural': 'historical resources'},
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldatadefinition',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalhouseholdincome',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalresource',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
