# Generated by Django 4.1.1 on 2022-10-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_alter_historicaluniversity_logo_and_more'),
        ('home', '0021_alter_historicalcontact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
    ]
