# Generated by Django 4.1.1 on 2022-10-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_historicalcollege_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluniversity',
            name='primarycolor',
            field=models.CharField(default='red', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaluniversity',
            name='secondarycolor',
            field=models.CharField(default='black', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='primarycolor',
            field=models.CharField(default='red', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='secondarycolor',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
