# Generated by Django 4.1.1 on 2022-10-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_historicaluniversity_primarycolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluniversity',
            name='logo',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
