# Generated by Django 4.1.1 on 2022-10-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_historicaluniversity_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluniversity',
            name='logo',
            field=models.CharField(default='https://www.unomaha.edu/_files/images/logo-subsite-o-2.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.CharField(default='https://www.unomaha.edu/_files/images/logo-subsite-o-2.png', max_length=1000),
        ),
    ]
