# Generated by Django 4.1.1 on 2022-10-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_alter_historicaluniversity_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluniversity',
            name='slug',
            field=models.CharField(default='uno', max_length=50),
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.CharField(default='uno', max_length=50),
        ),
    ]
